# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 */2 * * *"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build    
    - uses: actions/checkout@v2.3.4
    - name: Gradle Cache
      uses: burrunan/gradle-cache-action@v1.10
      with:
        gradle-version: nightly
